version: '3.4'

services:

  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
     
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_HOST_AUTH_METHOD: trust

