version: '3.4'

services:
  web:
    env_file: .env
    build: 
      dockerfile: Dockerfile.django
    volumes:
      - .:/app
    depends_on:
      - db
     
  db:
    env_file: .env
    image: postgres
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASS
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_HOST_AUTH_METHOD: $DATABASE_AUTH_METHOD

  proxyserver:
    build:
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - web

    
