version: '3.4'

services:
  parking:
    image: parking
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
  database:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: