# Generated by Django 4.2.1 on 2023-05-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='type',
            field=models.CharField(choices=[('Motorbike', 'Motorbike'), ('Car', 'Car'), ('Van', 'Van')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Motorbike', 'Motorbike'), ('Car', 'Car'), ('Van', 'Van')], max_length=50),
        ),
    ]
